#!/usr/bin/perl

# 	script to plot a motion file
#	rev 0 	2/21/09		original from T Brosnan and M Alley
#	rev 1	11/15/09	change scaling to 2 mm

use Tie::File;

my $fname;
if (defined ($ARGV[0])) {
  $fname = $ARGV[0];
}
else { 
  print "Oops!  I need a motion file name\n";
  exit;
}

my @lines;
tie(@lines, Tie::File, $fname, mode => O_RDWR) or die "Cannot open file $fname: $!\n";
##print "Number of lines is: $#lines\n";
##print "And the last is: $lines[$#lines]\n";

open(GNUPLOT, "| gnuplot -persist")     || die "cannot run gnuplot: $!";
print GNUPLOT "set xlabel 'time frame' \n";
print GNUPLOT "set ylabel 'translation, mm' \n";
print GNUPLOT "set grid \n";
print GNUPLOT "set title \"$lines[$#lines]\" \n";
print GNUPLOT "plot [] [-2:2] '$fname' using 1 title 'x' with lines, '$fname' using 2 title 'y' with lines, '$fname' using 3 title 'z' with lines \n";
close

exit;

